### ISSUE TITLE
MinIO/S3 services appear to be broken

### ISSUE THREAD

**Issue by FlorentBedecarratsNM** [InseeFrLab/sspcloud#12]
Hi there,
The MinIO service worked fine until this morning, but as I am re-connecting tonight, it appears to be down:
- The icon "My files" disappeared from the left menu on Onyxia UI (see screenshot below),
- connecting with SSO to the MinIO console returns an error 504,
- fetching files through my applications with aws.s3 R package returns "Bucket 'fbedecarrats' doesn't exist".

Just to inform you in case it is not due to intended operations on your side.
Thanks!
![Screenshot from 2022-02-08 23-20-12](https://user-images.githubusercontent.com/75624058/153085435-3e8f1533-d6e8-456b-8148-9a5a1f68bbca.png)

**Comment by olevitt** [comment]
Hi,

Thanks for the report. 
Since a few weeks ago, our minIO instance is experiencing huge performance issues. 
We are still trying to understand and fix the issue.
We currently have narrowed it down to the authentication mecanism of minIO but are still investigating. Some investigations required us to remove files feature from Onyxia. 
Data is considered safe at the moment, no data loss is expected at this time but we currently have not decided on the plan to bring a fully functional minIO back online. We may have to fully backup, rebuild and restore it which would take some Time, probably around 1 day. So expect downtime in the next days.
If you have access to the tchap messaging system, we are posting updates there (#sspcloud Channel)

**Comment by FlorentBedecarratsNM** [comment]
Thanks, no need for backup on my side (but I guess you have much heavier "clients"). No emergency either. I'll keep on working on local/shinyapps for my current tunnings and I'll be back to Onyxia when it's solved on your side. Bon courage !

**Comment by olevitt** [comment]
MinIO is back !

**Comment by FlorentBedecarratsNM** [comment]
Wonderful! Thanks and congratulations to the team.

**Comment by FlorentBedecarratsNM** [comment]
Just a note: it seems that the MinIO service accounts created before the MinIO reset have been deleted. Users should re-create them in the MinIO console and edit their secrets kubernetes with  `kubectl edit secrets <mysecret>`.
